export enum Constants {
  SET_ROLE = 'SET_ROLE',
  ADD_CALORIES = 'ADD_CALORIES',
  ADD_SCORE = 'ADD_SCORE',
  ADD_WORKOUT = 'ADD_WORKOUT',
  ADD_CHALLENGE = 'ADD_CHALLENGE',
  START_FROM_SCRATCH = 'START_FROM_SCRATCH',
  AUTOMATICALLY_GENERATE = 'AUTOMATICALLY_GENERATE',
  MARK_DAY_AS_DONE = 'MARK_DAY_AS_DONE',
  SET_WORKOUT_FOR_DAY = 'SET_WORKOUT_FOR_DAY',
}
