export enum Constants {
  GET_USERS_SUCCESS = 'GET_USERS_SUCCESS',
  GET_USERS_ERROR = 'GET_USERS_ERROR',
  GET_USERS_LOADING = 'GET_USERS_LOADING',
  REGISTER_USER_LOADING = 'REGISTER_USER_LOADING',
  REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS',
  REGISTER_USER_ERROR = 'REGISTER_USER_ERROR',
}
